version: "3.8"

services:
  sentinel:
    build: .
    ports:
      - "8080:8080"
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    volumes:
      - ./data:/root/data
      - ./config.yaml:/root/config.yaml
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8080/api/services",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Example services to monitor (for testing)
  nginx-test:
    image: nginx:alpine
    ports:
      - "8081:80"
    restart: unless-stopped

  redis-test:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server --requirepass testpassword

volumes:
  sentinel-data:
    driver: local
